// Site adapter: YouTube. Registers itself on the shared namespace.
// Content scripts can't use ES imports without a build step, so every file
// attaches to globalThis.TDDW and the manifest loads them in order
// (youtube-transcript.js provides fetchYouTubeTranscript/pickCaptionTrack).
globalThis.TDDW = globalThis.TDDW || { adapters: [] };

(() => {
  // Keep the transcript payload well inside message/context limits.
  const MAX_TRANSCRIPT_CHARS = 60000;

  // ytInitialPlayerResponse is embedded as a JS object literal in the watch
  // page HTML. Regex is too fragile for nested braces — walk the braces with
  // string awareness instead.
  function extractPlayerResponse(html) {
    const marker = 'ytInitialPlayerResponse = ';
    const start = html.indexOf(marker);
    if (start === -1) return null;
    const jsonStart = html.indexOf('{', start);
    if (jsonStart === -1) return null;
    let depth = 0;
    let inStr = false;
    let esc = false;
    for (let i = jsonStart; i < html.length; i++) {
      const c = html[i];
      if (inStr) {
        if (esc) esc = false;
        else if (c === '\\') esc = true;
        else if (c === '"') inStr = false;
      } else if (c === '"') {
        inStr = true;
      } else if (c === '{') {
        depth++;
      } else if (c === '}') {
        depth--;
        if (depth === 0) return JSON.parse(html.slice(jsonStart, i + 1));
      }
    }
    return null;
  }

  // Fallback strategy: caption track URL scraped from the watch page. YouTube
  // gates this behind a proof-of-origin token for most videos and returns an
  // EMPTY 200 body without one — treat that as failure, not JSON.
  async function fetchViaPageCaptions(cutoffMs) {
    const pageRes = await fetch(location.href, { credentials: 'same-origin' });
    if (!pageRes.ok) throw new Error(`watch page fetch failed (${pageRes.status})`);
    const player = extractPlayerResponse(await pageRes.text());
    const tracks = player?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!tracks?.length) return null;

    const track = globalThis.TDDW.pickCaptionTrack(tracks);
    const url = new URL(track.baseUrl, location.origin);
    url.searchParams.set('fmt', 'json3');
    const res = await fetch(url, { credentials: 'same-origin' });
    if (!res.ok) throw new Error(`timedtext failed (${res.status})`);
    const body = await res.text();
    if (!body) throw new Error('timedtext returned an empty body (POT-gated)');
    const data = JSON.parse(body);

    const lines = [];
    for (const ev of data.events || []) {
      if (!ev.segs || ev.tStartMs > cutoffMs) continue;
      const text = ev.segs.map((s) => s.utf8 || '').join('').replace(/\s+/g, ' ').trim();
      // Prefix each line with its [m:ss] timestamp — same contract as the
      // InnerTube path — so the recap prompt gets seekable time chips instead of
      // the model inventing them.
      if (text) lines.push(`[${globalThis.TDDW.formatTimestamp(ev.tStartMs)}] ${text}`);
    }
    return lines.length
      ? { lines, language: track.languageCode || 'unknown', autoGenerated: track.kind === 'asr' }
      : null;
  }

  // If the transcript is too long, sample lines evenly so the recap still
  // covers the whole span (start → now) instead of just the beginning.
  function capTranscript(lines) {
    const text = lines.join('\n');
    if (text.length <= MAX_TRANSCRIPT_CHARS) return { text, truncated: false };
    const keepRatio = MAX_TRANSCRIPT_CHARS / text.length;
    const sampled = lines.filter((_, i) => Math.floor(i * keepRatio) !== Math.floor((i - 1) * keepRatio));
    // Even sampling can still overshoot when line lengths vary. Trim whole lines
    // from the OLDEST end so the most recent events (closest to "now", what the
    // user actually wants caught up on) always survive and no line is cut
    // mid-token — a naive slice(0, MAX) would drop the newest lines instead.
    const kept = [];
    let total = 0;
    for (let i = sampled.length - 1; i >= 0; i--) {
      const len = sampled[i].length + 1; // +1 for the joining newline
      if (kept.length && total + len > MAX_TRANSCRIPT_CHARS) break;
      kept.unshift(sampled[i]);
      total += len;
    }
    console.warn(`[TD;DW] transcript truncated: kept ${kept.length} of ${lines.length} lines`);
    return { text: kept.join('\n'), truncated: true };
  }

  globalThis.TDDW.adapters.push({
    service: 'youtube',

    matches(loc) {
      return loc.hostname.endsWith('youtube.com');
    },

    // Read lazily at activation time — avoids YouTube SPA-navigation staleness.
    async getVideoState() {
      if (!location.pathname.startsWith('/watch')) return null;
      const video = document.querySelector('video.html5-main-video') || document.querySelector('video');
      if (!video) return null;
      globalThis.TDDW.activeVideo = video;

      const titleEl = document.querySelector('ytd-watch-metadata h1 yt-formatted-string');
      const title =
        titleEl?.textContent?.trim() ||
        document.title.replace(/ - YouTube$/, '').trim() ||
        null;

      return {
        service: 'YouTube',
        title,
        episodeInfo: null,
        currentTimeSeconds: video.currentTime,
        durationSeconds: Number.isFinite(video.duration) ? video.duration : null
      };
    },

    // Real captions up to the timestamp. Primary: the InnerTube ANDROID-client
    // route (see youtube-transcript.js). Fallback: caption URLs scraped from
    // the watch page. Returns null when the video simply has no captions.
    async getTranscriptUpTo(seconds) {
      const videoId = new URLSearchParams(location.search).get('v');
      if (!videoId) return null;
      const cutoffMs = seconds * 1000;

      let result = null;
      try {
        result = await globalThis.TDDW.fetchYouTubeTranscript(videoId, cutoffMs);
      } catch (err) {
        console.warn('[TD;DW] innertube transcript failed, trying page captions:', err.message);
      }
      if (!result) {
        result = await fetchViaPageCaptions(cutoffMs);
      }
      if (!result) return null;

      const { text, truncated } = capTranscript(result.lines);
      return { text, language: result.language, autoGenerated: result.autoGenerated, truncated };
    }
  });
})();
