// Spoiler safety lives here. Expect to iterate on this file more than any
// other — it is the product.

const BULLET_COUNTS = { short: '3-5', medium: '5-8', detailed: '8-12' };

export const NO_KNOWLEDGE_TOKEN = 'NO_KNOWLEDGE';

export function formatTime(seconds) {
  if (!Number.isFinite(seconds)) return 'an unknown time';
  const s = Math.floor(seconds);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  const mm = String(m).padStart(2, '0');
  const ss = String(sec).padStart(2, '0');
  return h > 0 ? `${h}:${mm}:${ss}` : `${m}:${ss}`;
}

export function buildRecapMessages(videoState, config) {
  const { service, title, episodeInfo, currentTimeSeconds, durationSeconds } = videoState;
  const now = formatTime(currentTimeSeconds);
  const total = formatTime(durationSeconds);
  const pct = Number.isFinite(currentTimeSeconds) && Number.isFinite(durationSeconds) && durationSeconds > 0
    ? ` (~${Math.round((currentTimeSeconds / durationSeconds) * 100)}% through)`
    : '';
  const bullets = BULLET_COUNTS[config.summaryLength] || BULLET_COUNTS.medium;
  const episode = episodeInfo ? ` (${episodeInfo})` : '';

  const system = [
    `You are TD;DW, a spoiler-free recap assistant.`,
    `The user is watching "${title}"${episode} on ${service} and is currently at ${now} of ${total}${pct}.`,
    `HARD RULES:`,
    `(1) Recap ONLY events that occur before ${now}.`,
    `(2) Never reveal, hint at, or foreshadow anything that happens after that point — no "little does she know", no thematic winks, no naming characters who have not yet appeared.`,
    `(3) If you are unsure whether something happens before or after ${now}, omit it entirely.`,
    `(4) Identify the work using ALL available clues together: the title, the platform (${service}), and the runtime of ${total}. Titles are often shared by multiple works — pick the one whose runtime and platform fit. For example, a 2-hour runtime means a feature film, not a series episode.`,
    `(4b) Only if no work you know plausibly matches these clues${episodeInfo ? ' (including the episode)' : ''}, reply with the single token ${NO_KNOWLEDGE_TOKEN} on the first line, then one sentence saying you don't know it. Never guess or fabricate plot for an unrecognized work — but do not refuse merely because a title is ambiguous when the runtime settles it.`,
    `(5) Format: at most ${bullets} concise bullet points in plain text, one per line, each starting with "- ". If little has happened yet, use fewer bullets — even a single bullet is a complete answer.`,
    `(6) You may bold one or two key character or place names per bullet with **double asterisks**; use no other formatting. Never include timestamps — you do not know exact timings.`,
    `(7) Output ONLY the bullet lines. No preamble, no closing remarks, no commentary about how much material is available, and no notes about your limitations.`
  ].join(' ');

  const user = `Catch me up on "${title}"${episode} up to ${now}.`;

  return [
    { role: 'system', content: system },
    { role: 'user', content: user }
  ];
}

export function buildTranscriptMessages(videoState, config) {
  const { service, title, episodeInfo, currentTimeSeconds, durationSeconds, transcript } = videoState;
  const now = formatTime(currentTimeSeconds);
  const total = formatTime(durationSeconds);
  const bullets = BULLET_COUNTS[config.summaryLength] || BULLET_COUNTS.medium;
  const episode = episodeInfo ? ` (${episodeInfo})` : '';

  const system = [
    `You are TD;DW, a spoiler-free recap assistant.`,
    `The user is watching "${title}"${episode} on ${service} and is currently at ${now} of ${total}.`,
    `The user will provide the video's caption transcript covering ONLY the portion from the start up to ${now}.`,
    `RULES:`,
    `(1) Recap only what is in the transcript — do not add outside knowledge or speculate about what comes after ${now}.`,
    transcript?.autoGenerated === false
      ? `(2) Stay faithful to the transcript.`
      : `(2) The captions may be auto-generated and contain recognition errors — read through obvious mistranscriptions, but never invent content to fill gaps.`,
    transcript?.truncated
      ? `(3) The transcript was evenly sampled to fit; there may be small gaps between lines.`
      : ``,
    `(4) Format: at most ${bullets} concise bullet points in plain text, one per line, each starting with "- ". If little has happened yet, use fewer bullets — even a single bullet is a complete answer.`,
    `(5) Every transcript line begins with its [m:ss] timestamp. Start each bullet with the [m:ss] timestamp (copied from the transcript) of the moment that bullet covers, in chronological order.`,
    `(6) You may bold one or two key names or terms per bullet with **double asterisks**; use no other formatting.`,
    `(7) Output ONLY the bullet lines. No preamble, no closing remarks, no commentary about how much or little transcript is available, and no notes about your limitations.`
  ].filter(Boolean).join(' ');

  const user = `Transcript of "${title}"${episode} up to ${now}:\n\n${transcript.text}\n\nCatch me up.`;

  return [
    { role: 'system', content: system },
    { role: 'user', content: user }
  ];
}

// Follow-up Q&A: the user asks free-form questions about the title after the
// recap is shown. Like the recap, answers stay spoiler-free by default
// (config.spoilerFreeAnswers, on by default) — bounded to events before `now`.
// Turning it off lets answers draw on the whole plot for people who want the
// full picture. `history` is the prior [{ question, answer }] turns of THIS
// panel session.
export function buildQuestionMessages(videoState, config, recapText, history, question) {
  const { service, title, episodeInfo, currentTimeSeconds, durationSeconds, transcript } = videoState;
  const now = formatTime(currentTimeSeconds);
  const total = formatTime(durationSeconds);
  const episode = episodeInfo ? ` (${episodeInfo})` : '';

  const common = [
    `You are TD;DW's follow-up assistant.`,
    `The user is watching "${title}"${episode} on ${service} and is currently at ${now} of ${total}.`,
    `They already have a recap; now they're asking follow-up questions.`
  ];

  const spoilerFree = config.spoilerFreeAnswers
    ? [
        `SPOILER RULES:`,
        `(1) Answer ONLY about events up to ${now}. Never reveal, hint at, or foreshadow anything after that point.`,
        `(2) If the honest answer would require information from after ${now}, do not give it — reply with one short sentence like "That happens later than where you are — I won't spoil it."`,
        `(3) If you are unsure whether something happens before or after ${now}, treat it as later and don't reveal it.`
      ]
    : [
        `The user has explicitly opted into COMPLETE answers: you MAY draw on the full plot and your general knowledge, INCLUDING events after ${now}. Do not withhold or hedge to avoid spoilers — answer the question fully.`
      ];

  const format = [
    `FORMAT:`,
    `(a) Answer directly in 1-3 sentences of plain, conversational prose — no bullet points, no preamble, no closing remarks.`,
    `(b) When a transcript is provided below, prefer it for specifics about what has actually been shown on screen.`,
    `(c) You may bold one or two key names or terms with **double asterisks**; use no other formatting.`,
    `(d) If you genuinely don't know, say so briefly rather than inventing an answer.`
  ];

  const system = [...common, ...spoilerFree, ...format].join(' ');

  let contextBlock = `Here is the spoiler-free recap you gave me for "${title}"${episode} up to ${now}:\n\n${recapText}`;
  if (transcript?.text) {
    contextBlock += `\n\nCaption transcript up to ${now} (use for specifics about what's been shown):\n\n${transcript.text}`;
  }

  // Keep a sliding window of the most recent turns. The recap + transcript
  // already dominate the token budget; unbounded history would only add latency
  // and risk overflowing smaller/local context windows.
  const priorTurns = (history || []).slice(-10).flatMap((turn) => [
    { role: 'user', content: turn.question },
    { role: 'assistant', content: turn.answer }
  ]);

  return [
    { role: 'system', content: system },
    { role: 'user', content: contextBlock },
    { role: 'assistant', content: 'Got it — ask me anything about it.' },
    ...priorTurns,
    { role: 'user', content: question }
  ];
}
