// Spoiler safety lives here. Expect to iterate on this file more than any
// other — it is the product.

const BULLET_COUNTS = { short: '3-5', medium: '5-8', detailed: '8-12' };

export const NO_KNOWLEDGE_TOKEN = 'NO_KNOWLEDGE';

export function formatTime(seconds) {
  if (!Number.isFinite(seconds)) return 'an unknown time';
  const s = Math.floor(seconds);
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const sec = s % 60;
  const mm = String(m).padStart(2, '0');
  const ss = String(sec).padStart(2, '0');
  return h > 0 ? `${h}:${mm}:${ss}` : `${m}:${ss}`;
}

export function buildRecapMessages(videoState, config) {
  const { service, title, episodeInfo, currentTimeSeconds, durationSeconds } = videoState;
  const now = formatTime(currentTimeSeconds);
  const total = formatTime(durationSeconds);
  const pct = Number.isFinite(currentTimeSeconds) && Number.isFinite(durationSeconds) && durationSeconds > 0
    ? ` (~${Math.round((currentTimeSeconds / durationSeconds) * 100)}% through)`
    : '';
  const bullets = BULLET_COUNTS[config.summaryLength] || BULLET_COUNTS.medium;
  const episode = episodeInfo ? ` (${episodeInfo})` : '';

  const system = [
    `You are TD;DW, a spoiler-free recap assistant.`,
    `The user is watching "${title}"${episode} on ${service} and is currently at ${now} of ${total}${pct}.`,
    `HARD RULES:`,
    `(1) Recap ONLY events that occur before ${now}.`,
    `(2) Never reveal, hint at, or foreshadow anything that happens after that point — no "little does she know", no thematic winks, no naming characters who have not yet appeared.`,
    `(3) If you are unsure whether something happens before or after ${now}, omit it entirely.`,
    `(4) Identify the work using ALL available clues together: the title, the platform (${service}), and the runtime of ${total}. Titles are often shared by multiple works — pick the one whose runtime and platform fit. For example, a 2-hour runtime means a feature film, not a series episode.`,
    `(4b) Only if no work you know plausibly matches these clues${episodeInfo ? ' (including the episode)' : ''}, reply with the single token ${NO_KNOWLEDGE_TOKEN} on the first line, then one sentence saying you don't know it. Never guess or fabricate plot for an unrecognized work — but do not refuse merely because a title is ambiguous when the runtime settles it.`,
    `(5) Format: at most ${bullets} concise bullet points in plain text, one per line, each starting with "- ". If little has happened yet, use fewer bullets — even a single bullet is a complete answer.`,
    `(6) You may bold one or two key character or place names per bullet with **double asterisks**; use no other formatting. Never include timestamps — you do not know exact timings.`,
    `(7) Output ONLY the bullet lines. No preamble, no closing remarks, no commentary about how much material is available, and no notes about your limitations.`
  ].join(' ');

  const user = `Catch me up on "${title}"${episode} up to ${now}.`;

  return [
    { role: 'system', content: system },
    { role: 'user', content: user }
  ];
}

export function buildTranscriptMessages(videoState, config) {
  const { service, title, episodeInfo, currentTimeSeconds, durationSeconds, transcript } = videoState;
  const now = formatTime(currentTimeSeconds);
  const total = formatTime(durationSeconds);
  const bullets = BULLET_COUNTS[config.summaryLength] || BULLET_COUNTS.medium;
  const episode = episodeInfo ? ` (${episodeInfo})` : '';

  const system = [
    `You are TD;DW, a spoiler-free recap assistant.`,
    `The user is watching "${title}"${episode} on ${service} and is currently at ${now} of ${total}.`,
    `The user will provide the video's caption transcript covering ONLY the portion from the start up to ${now}.`,
    `RULES:`,
    `(1) Recap only what is in the transcript — do not add outside knowledge or speculate about what comes after ${now}.`,
    transcript?.autoGenerated === false
      ? `(2) Stay faithful to the transcript.`
      : `(2) The captions may be auto-generated and contain recognition errors — read through obvious mistranscriptions, but never invent content to fill gaps.`,
    transcript?.truncated
      ? `(3) The transcript was evenly sampled to fit; there may be small gaps between lines.`
      : ``,
    `(4) Format: at most ${bullets} concise bullet points in plain text, one per line, each starting with "- ". If little has happened yet, use fewer bullets — even a single bullet is a complete answer.`,
    `(5) Every transcript line begins with its [m:ss] timestamp. Start each bullet with the [m:ss] timestamp (copied from the transcript) of the moment that bullet covers, in chronological order.`,
    `(6) You may bold one or two key names or terms per bullet with **double asterisks**; use no other formatting.`,
    `(7) Output ONLY the bullet lines. No preamble, no closing remarks, no commentary about how much or little transcript is available, and no notes about your limitations.`
  ].filter(Boolean).join(' ');

  const user = `Transcript of "${title}"${episode} up to ${now}:\n\n${transcript.text}\n\nCatch me up.`;

  return [
    { role: 'system', content: system },
    { role: 'user', content: user }
  ];
}
